version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
      - npm install -g sonarqube-scanner

  build:
    commands:
      - npm run test
      - sonar-scanner  # Uses sonar-project.properties
      - npm run build  # Builds frontend (e.g., React/Vue)

  post_build:
    commands:
      - aws s3 sync build/ s3://aws-bucket-repo --delete  # Deploys to S3

env:
  secrets-manager:
    SONAR_TOKEN: "git/sonar/s3"  # Name of secret in Secrets Manager
