version: 0.2

env:
  variables:
    SONARQUBE_HOST_URL: "http://13.50.247.9:9000"
    SONARQUBE_TOKEN: "sqp_411d29d0da5aa8788c08d6340ef42224dc055dbb"
    S3_BUCKET: "aws-code-pipe-git"
    AWS_REGION: "eu-north-1"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Node.js dependencies...
      - npm install
      - echo Downloading SonarScanner...
      - curl -sS -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-*/ sonar-scanner
      - export PATH=$PATH:$(pwd)/sonar-scanner/bin

  pre_build:
    commands:
      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=mahesh \
          -Dsonar.sources=.
          -Dsonar.host.url=$SONARQUBE_HOST_URL \
          -Dsonar.login=$SONARQUBE_TOKEN \
          -Dsonar.projectVersion=$CODEBUILD_BUILD_NUMBER

  build:
    commands:
      - echo "Building frontend..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./build/ s3://$S3_BUCKET/ --region $AWS_REGION --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes
