version: 0.2

env:
  variables:
    S3_BUCKET: "mahesh-new-sonar"
    BUILD_DIR: "build"
  secrets-manager:
    SONAR_TOKEN: "sonar-secret1:SONAR_TOKEN"

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

      - echo Installing SonarScanner...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      - echo Running SonarQube Analysis...
      - sonar-scanner \
          -Dsonar.projectKey=sonar \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://18.229.117.21:9000 \
          -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo Starting build...
      - npm run build || { echo "Build failed"; exit 1; }

  post_build:
    commands:
      - echo "Checking build output..."
      - ls -la $BUILD_DIR
      - echo Deploying to S3...
      - aws s3 sync $BUILD_DIR/ s3://$S3_BUCKET/ --delete
