version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "sonar-secret1:SONAR_TOKEN"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Sonar Scanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  build:
    commands:
      - echo "Running SonarQube analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=frontend-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://18.231.115.242:9000 \
          -Dsonar.login=$SONAR_TOKEN
      - echo "SonarQube scan complete"

  post_build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync public/ s3://your-s3-bucket-name/ --delete
