version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "sonar-secret:SONAR_TOKEN"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing SonarScanner...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  build:
    commands:
      - echo Running Sonar Scanner...
      - sonar-scanner

artifacts:
  files:
    - '**/*'
  base-directory: src  # This is the folder that will be deployed to S3

