version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: "sonar-secret1:SONAR_TOKEN"
  variables:
    S3_BUCKET: "mahesh-new-sonar"

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo Installing Node packages...
      - npm install
      - echo Installing SonarScanner...
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      - echo Running SonarQube scan...
      - sonar-scanner \
          -Dsonar.projectKey=sonar \
          -Dsonar.sources=src \
          -Dsonar.host.url=http://18.229.117.21:9000 \
          -Dsonar.login=$SONAR_TOKEN

  build:
    commands:
      - echo Building React app...
      - npm run build

  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: build
