version: 0.2

env:
  variables:
    S3_BUCKET: "aws-code-pipe-git"   # ✅ Your S3 bucket name

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Downloading SonarScanner..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - mv sonar-scanner-5.0.1.3006-linux sonar-scanner

  pre_build:
    commands:
      - echo "Running SonarQube analysis..."
      - ./sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=your_project_key \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://<SONAR_HOST>:9000 \
          -Dsonar.login=<SONAR_TOKEN> \
          -Dsonar.verbose=true

  build:
    commands:
      - echo "Building frontend app..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 cp ./build s3://$S3_BUCKET/ --recursive

artifacts:
  files:
    - '**/*'
