version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Contents of working directory:"
      - ls -la
      - npm install

  build:
    commands:
      - npm run build
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - aws s3 sync build/ s3://aws-bucket-repo --delete
